---
abstract: 'Run command-line sessions to network appliances'
author:
  - 'Oliver Gorwits C<< <oliver.gorwits@oucs.ox.ac.uk> >>'
build_requires:
  Test::More: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
distribution_type: module
generated_by: 'Module::Install version 0.76'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Appliance-Session
no_index:
  directory:
    - inc
    - t
    - examples
recommends:
  Devel::REPL: 0
  Devel::REPL::Plugin::NAS: 0
  IO::Interactive: 0
requires:
  Class::Accessor: 0.25
  Class::Accessor::Fast::Contained: 0
  Class::Data::Inheritable: 0
  Exception::Class: 0
  IO::Pty: 0
  Net::Appliance::Phrasebook: 1.7
  Net::Telnet: 0
  UNIVERSAL::require: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
version: 1.33
