---
abstract: 'Run command-line sessions to network appliances'
author:
  - 'Oliver Gorwits <oliver@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200000, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Appliance-Session
requires:
  Carp: 0
  Class::Accessor::Fast::Contained: 0
  Class::Data::Inheritable: 0
  Exception::Class: 0
  Exporter: 0
  FileHandle: 0
  IO::Pty: 0
  Net::Appliance::Phrasebook: 1.2
  Net::Telnet: 0
  POSIX: 0
  Symbol: 0
  UNIVERSAL::require: 0
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Net-Appliance-Session
  homepage: https://github.com/ollyg/Net-Appliance-Session/wiki
  repository: git://github.com/ollyg/Net-Appliance-Session.git
version: 2.110470
